name: Backend deployment
run-name: Backend deployment update triggered by ${{ github.actor }} :- ${{ github.run_number }}

on:
  push:
    branches:
      - deployment
    paths:
      - .github/workflows/backendDeploy.yml
      - backend/**

jobs:
  build:
    name: Backend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    timeout-minutes: 10
    strategy:
      matrix:
        services:
          - address-service
          - appointment-service
          - card-service
          - cloud-gateway
          - lab-service
          - patient-service
          - service-registry
          - test-lab-service
          - test-service
          - user-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "11"

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.services }}-${{ hashFiles(join(matrix.services, '/**/pom.xml')) }}
          restore-keys: |
            ${{ runner.os }}-maven-



      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the docker image to ghcr
        uses: docker/build-push-action@v4
        with:
          context: backend/${{ matrix.services }}
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp-backend-${{ matrix.services }}:${{ github.run_number }}
